import Papa from 'papaparse';
import { computeMarginPercent, extractEmployeeCount, extractNetResult, extractRevenue } from './rubrics';
import type { NbbAccountingData, NbbAnnualAccountSummary } from './types';

const CONSULT_BASE_URL = 'https://consult.cbso.nbb.be';
const DEFAULT_REQUEST_DELAY_MS = 750;
const DEFAULT_RETRIES = 5;

let requestQueue = Promise.resolve();

export type PublicConsultRequestOptions = {
  requestDelayMs?: number;
  retries?: number;
};

export class NbbPublicConsultError extends Error {
  constructor(message: string, readonly status?: number) {
    super(message);
    this.name = 'NbbPublicConsultError';
  }
}

type PublishedDeposit = {
  id: string;
  reference: string;
  periodEndDateYear: number;
  depositDate?: string;
  enterpriseName?: string;
};

type PublishedDepositResponse = { content?: PublishedDeposit[] };

function normalizeEnterpriseNumber(input: string): string {
  return input.replaceAll(/\D/g, '');
}

function parseCsvAccountingData(csv: string): NbbAccountingData {
  const rows = Papa.parse<string[]>(csv, { skipEmptyLines: true }).data;
  const values = new Map(rows.filter((row) => row.length >= 2).map(([key, value]) => [key, value]));
  return {
    EnterpriseName: values.get('Entity name'),
    ReferenceNumber: values.get('Reference number'),
    Rubrics: rows
      .filter(([code]) => /^\d/.test(code ?? ''))
      .map(([Code, Value]) => ({ Code, Value, Period: 'N' })),
  };
}

function delay(milliseconds: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function retryDelay(response: Response | undefined, attempt: number): number {
  const retryAfter = response?.headers.get('retry-after');
  const seconds = retryAfter ? Number.parseInt(retryAfter, 10) : Number.NaN;
  return Number.isFinite(seconds) ? seconds * 1_000 : Math.min(30_000, 2_000 * 2 ** attempt);
}

async function throttledFetch(url: string, headers: HeadersInit, fetchImpl: typeof fetch, options: PublicConsultRequestOptions): Promise<Response> {
  const requestDelayMs = Math.max(0, options.requestDelayMs ?? DEFAULT_REQUEST_DELAY_MS);
  const retries = Math.max(0, options.retries ?? DEFAULT_RETRIES);
  let lastError: unknown;

  for (let attempt = 0; attempt <= retries; attempt += 1) {
    let releaseQueue: () => void;
    const queued = requestQueue;
    requestQueue = new Promise<void>((resolve) => { releaseQueue = resolve; });
    await queued;
    let response: Response | undefined;
    try {
      response = await fetchImpl(url, { headers });
      if (response.ok) return response;
      const error = new NbbPublicConsultError(`NBB public consultation request failed (${response.status})`, response.status);
      if (response.status !== 429 && response.status !== 503) throw error;
      lastError = error;
    } catch (error) {
      lastError = error;
      if (error instanceof NbbPublicConsultError && error.status !== 429 && error.status !== 503) throw error;
    } finally {
      setTimeout(releaseQueue!, requestDelayMs);
    }

    if (attempt < retries) await delay(retryDelay(response, attempt));
  }

  throw lastError instanceof Error ? lastError : new NbbPublicConsultError('NBB public consultation request failed');
}

async function getJson<T>(url: string, fetchImpl: typeof fetch, options: PublicConsultRequestOptions): Promise<T> {
  return (await throttledFetch(url, { Accept: 'application/json' }, fetchImpl, options)).json() as Promise<T>;
}

/** Reads the CSV export generated by NBB from the published XBRL filing. */
export async function fetchPublicConsultFinancials(enterpriseNumber: string, requestedYears: number[], fetchImpl: typeof fetch = fetch, options: PublicConsultRequestOptions = {}): Promise<{ enterpriseName?: string; years: NbbAnnualAccountSummary[] }> {
  const number = normalizeEnterpriseNumber(enterpriseNumber);
  if (number.length !== 10) throw new Error('Invalid enterprise number');
  const parameters = new URLSearchParams({ page: '0', size: '100', enterpriseNumber: number, sort: 'periodEndDate,desc', });
  const deposits = (await getJson<PublishedDepositResponse>(`${CONSULT_BASE_URL}/api/rs-consult/published-deposits?${parameters}`, fetchImpl, options)).content ?? [];
  const selected = requestedYears.map((year) => deposits.find((deposit) => deposit.periodEndDateYear === year)).filter((deposit): deposit is PublishedDeposit => deposit !== undefined);
  const enterpriseName = selected[0]?.enterpriseName;
  const years: NbbAnnualAccountSummary[] = [];

  for (const deposit of selected) {
    try {
      const response = await throttledFetch(`${CONSULT_BASE_URL}/api/external/broker/public/deposits/consult/csv/${deposit.id}`, {}, fetchImpl, options);
      const accountingData = parseCsvAccountingData(await response.text());
      const revenue = extractRevenue(accountingData.Rubrics);
      const netResult = extractNetResult(accountingData.Rubrics);
      years.push({ fiscalYear: deposit.periodEndDateYear, referenceNumber: deposit.reference, revenue, netResult, marginPercent: computeMarginPercent(revenue, netResult), employeeCount: extractEmployeeCount(accountingData.Rubrics), currency: 'EUR', depositDate: deposit.depositDate });
    } catch {
      years.push({ fiscalYear: deposit.periodEndDateYear, referenceNumber: deposit.reference, revenue: null, netResult: null, marginPercent: null, employeeCount: null, currency: 'EUR', depositDate: deposit.depositDate, error: 'fetch_failed' });
    }
  }

  return { enterpriseName, years };
}